
/**
 * @file: path_planner_node.h
 * @brief: Contains the path planner ROS wrapper class
 * @author: ZhangDingkun
 * @date: 2024.06.08
 * @version: 1.0
 */
#ifndef RMP_PATH_PLANNER_PATH_PLANNER_NODE_H_
#define RMP_PATH_PLANNER_PATH_PLANNER_NODE_H_

#include <ros/ros.h>
#include <nav_core/base_global_planner.h>
#include <geometry_msgs/PoseStamped.h>
#include <nav_msgs/GetPlan.h>

#include "common/geometry/point.h"
#include "path_planner/path_planner.h"
#include "path_planner/path_processor/path_processor.h"
#include "trajectory_planner/trajectory_optimization/optimizer.h"

namespace rpp
{
namespace path_planner
{
class PathPlannerNode : public nav_core::BaseGlobalPlanner
{
public:
  /**
   * @brief Construct a new Path Planner object
   */
  PathPlannerNode();

  /**
   * @brief Construct a new Path Planner object
   * @param name        planner name
   * @param costmap_ros the cost map to use for assigning costs to trajectories
   */
  PathPlannerNode(std::string name, costmap_2d::Costmap2DROS* costmap_ros);

  /**
   * @brief Destroy the Path Planner object
   */
  ~PathPlannerNode() = default;

  /**
   * @brief Planner initialization
   * @param name       planner name
   * @param costmapRos costmap ROS wrapper
   */
  void initialize(std::string name, costmap_2d::Costmap2DROS* costmapRos);

  /**
   * @brief Planner initialization
   * @param name planner name
   */
  void initialize(std::string name);

  /**
   * @brief Plan a path given start and goal in world map
   * @param start start in world map
   * @param goal  goal in world map
   * @param plan  plan
   * @return true if find a path successfully, else false
   */
  bool makePlan(const geometry_msgs::PoseStamped& start, const geometry_msgs::PoseStamped& goal,
                std::vector<geometry_msgs::PoseStamped>& plan);

  /**
   * @brief Plan a path given start and goal in world map
   * @param start     start in world map
   * @param goal      goal in world map
   * @param plan      plan
   * @param tolerance error tolerance
   * @return true if find a path successfully, else false
   */
  bool makePlan(const geometry_msgs::PoseStamped& start, const geometry_msgs::PoseStamped& goal, double tolerance,
                std::vector<geometry_msgs::PoseStamped>& plan);
  /**
   * @brief Register planning service
   * @param req  request from client
   * @param resp response from server
   */
  bool makePlanService(nav_msgs::GetPlan::Request& req, nav_msgs::GetPlan::Response& resp);

  /**
   * @brief 根据全局规划方法配置对应的工具链（RDP、优化器、走廊等）
   */
  void configurePlannerToolchain();

  void publishInitialPlan(const PathPlanner::Points3d& optimized_plan);
  void publishInitialPlan2(const PathPlanner::Points3d& optimized_plan);

protected:
  /**
   * @brief Calculate plan from planning path
   * @param path path generated by global planner
   * @param plan plan transfromed from path, i.e. [start, ..., goal]
   * @return bool true if successful, else false
   */
  bool _getPlanFromPath(PathPlanner::Points3d& path, std::vector<geometry_msgs::PoseStamped>& plan);

protected:
  enum PLANNER_TYPE
  {
    GRAPH_PLANNER = 0,
    SAMPLE_PLANNER = 1,
    EVOLUTION_PLANNER = 2,
  };

protected:
  bool initialized_;                        // initialization flag
  costmap_2d::Costmap2DROS* costmap_ros_;   // costmap(ROS wrapper)
  std::string frame_id_;                    // costmap frame ID
  std::string planner_name_;                // planner name
  PLANNER_TYPE planner_type_;               // planner type
  std::string optimizer_name_;              // optimizer name
  std::shared_ptr<PathPlanner> g_planner_;  // global graph planner
  ros::Publisher plan_pub_;                 // path planning publisher
  ros::Publisher plan_opt_pub_;             // optimized path planning publisher
  ros::Publisher expand_pub_;               // nodes explorer publisher
  ros::Publisher points_pub_;               // key-points publisher
  ros::Publisher lines_pub_;                // polygons publisher
  ros::Publisher tree_pub_;                 // random search tree publisher
  ros::Publisher particles_pub_;            // evolutionary particles publisher
  ros::ServiceServer make_plan_srv_;        // planning service
  ros::Publisher prune_plan_pub_;   ////新增对比看原始路径与剪枝
  ros::Publisher initial_plan_pub_;                // 发布初始轨迹点的发布器
  ros::Publisher initial_plan_pub2_;                // 发布初始轨迹点的发布器
  ros::Publisher plan_time_pub_ ; // 发布规划时间的发布器

private:
  bool is_outline_;            // whether outline the boudary of map
  bool is_expand_;             // whether publish expand map or not
  bool show_safety_corridor_;  // whether visualize safety corridor
  bool use_safety_corridor_;   // whether use safety corridor constraint in optimization
  double tolerance_;           // tolerance
  double factor_;              // obstacle inflation factor
  bool is_initial_plan_recorded_;  // 标记是否已经记录了初始轨迹
  bool is_initial_plan_recorded2_;  // 标记是否已经记录了初始轨迹

private:
  std::shared_ptr<PathProcessor> pruner_;
  std::shared_ptr<rpp::trajectory_optimization::Optimizer> optimizer_;  // trajectory optimizer
  std::vector<PathPlanner::Point3d> initial_plan_;  // 用于存储初始轨迹点
  std::vector<PathPlanner::Point3d> initial_plan2_;  // 用于存储初始轨迹点
};
}  // namespace path_planner
}  // namespace rpp
#endif